// Reads a PDF's text on the phone, laid out in lines like `pdftotext -layout` (what the desktop's
// roadbook import uses): Mozilla pdf.js in a hidden WebView - the app's JS engine can't run pdf.js
// itself. pdf.js + the shared line layout come inline from config/pdfjsInline.js (generated by
// tools/gen_pdfjs_inline.js; tools/test_roadbook_pdf.js checks it finds the same controls as the
// desktop). The page gets no file access: a PDF is untrusted input.
//
// Mount it with the file's base64 when a PDF is to be read; it calls onDone once, then unmount it.
import React, { useEffect, useMemo, useRef } from 'react';
import { View } from 'react-native';
import { WebView, WebViewMessageEvent } from 'react-native-webview';

export interface PdfTextResult { ok: boolean; text?: string; pages?: number; error?: string }

const TIMEOUT_MS = 60000;

// Runs after pdf.js (module scripts run in order). Same getDocument options as the node test.
const RUN_JS = `
const post = m => window.ReactNativeWebView.postMessage(JSON.stringify(m));
(async () => {
  try {
    const bin = atob(window.PDF_B64);
    const data = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) data[i] = bin.charCodeAt(i);
    const task = window.pdfjsLib.getDocument({ data, isEvalSupported: false, disableFontFace: true,
                                               useSystemFonts: false, stopAtErrors: false });
    const doc = await task.promise;
    const pages = [];
    for (let p = 1; p <= doc.numPages; p++) pages.push((await (await doc.getPage(p)).getTextContent()).items);
    post({ ok: true, pages: doc.numPages, text: pdfTextLayout(pages) });
    task.destroy();
  } catch (e) {
    post({ ok: false, error: e && e.name === 'PasswordException' ? 'password' : String((e && e.message) || e) });
  }
})();`;

export function PdfTextReader({ base64, onDone }: { base64: string; onDone: (r: PdfTextResult) => void }) {
  const done = useRef(false);
  const finish = (r: PdfTextResult) => { if (!done.current) { done.current = true; onDone(r); } };

  const html = useMemo(() => {
    const P = require('../config/pdfjsInline');   // ~1.8 MB: only loaded when a PDF is read
    return '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body>' +
      `<script>window.PDF_B64=${JSON.stringify(base64)};</script>` +
      `<script>${P.PDF_LAYOUT_JS}</script>` +
      `<script type="module">${P.PDFJS_WORKER_JS}</script>` +
      `<script type="module">${P.PDFJS_LIB_JS}</script>` +
      `<script type="module">${RUN_JS}</script></body></html>`;
  }, [base64]);

  useEffect(() => {
    const id = setTimeout(() => finish({ ok: false, error: 'timed out' }), TIMEOUT_MS);
    return () => clearTimeout(id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const onMessage = (e: WebViewMessageEvent) => {
    try { finish(JSON.parse(e.nativeEvent.data)); } catch { finish({ ok: false, error: 'bad answer from the PDF reader' }); }
  };

  return (
    <View style={{ position: 'absolute', width: 1, height: 1, opacity: 0 }} pointerEvents="none">
      <WebView
        source={{ html, baseUrl: 'about:blank' }}
        originWhitelist={['*']}
        javaScriptEnabled
        allowFileAccess={false}
        allowFileAccessFromFileURLs={false}
        allowUniversalAccessFromFileURLs={false}
        onMessage={onMessage}
        onError={e => finish({ ok: false, error: e.nativeEvent.description || 'PDF reader failed to load' })}
      />
    </View>
  );
}
