#!/usr/bin/env node
// Writes android/src/config/pdfjsInline.js: Mozilla pdf.js (legacy build, pinned) + the shared
// line-layout code as strings, for the Android roadbook-PDF reader (a hidden WebView page - the
// app's JS engine can't run pdf.js itself). The desktop reads roadbook PDFs with `pdftotext
// -layout`; Android has no poppler.
//
// pdf.js is fetched with `npm pack` into a cache dir (the app's node_modules is shared with the
// main checkout, so nothing is installed there). The two .mjs files are inlined as <script
// type="module"> blocks: the worker first (it sets globalThis.pdfjsWorker, so pdf.js runs its
// "worker" on the page thread - file:// workers are blocked in a WebView), then the library with
// its trailing `export{...}` turned into `window.pdfjsLib = {...}`.
//
// Run: node tools/gen_pdfjs_inline.js      (re-run when bumping PDFJS_VERSION)
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const PDFJS_VERSION = '6.3.289';
const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'android', 'src', 'config', 'pdfjsInline.js');

/** The unpacked pdfjs-dist package dir (downloaded once into the OS temp dir). */
function pdfjsPackage() {
  const dir = path.join(os.tmpdir(), `sommet-pdfjs-${PDFJS_VERSION}`);
  const pkg = path.join(dir, 'package');
  if (!fs.existsSync(path.join(pkg, 'package.json'))) {
    fs.mkdirSync(dir, { recursive: true });
    execFileSync('npm', ['pack', `pdfjs-dist@${PDFJS_VERSION}`, '--silent'], { cwd: dir, stdio: ['ignore', 'ignore', 'inherit'] });
    execFileSync('tar', ['xzf', `pdfjs-dist-${PDFJS_VERSION}.tgz`], { cwd: dir });
  }
  return pkg;
}

function libAsGlobal(src) {
  const m = /export\s*\{([^}]*)\}\s*;?\s*$/.exec(src);
  if (!m) throw new Error('pdf.min.mjs: trailing export{...} not found');
  const props = m[1].split(',').map(s => s.trim()).filter(Boolean).map(s => {
    const [local, name] = s.split(/\s+as\s+/);
    return `${name || local}:${local}`;
  });
  return src.slice(0, m.index) + `window.pdfjsLib={${props.join(',')}};`;
}

function workerAsGlobal(src) {
  if (!/globalThis\.pdfjsWorker\s*=/.test(src)) throw new Error('pdf.worker.min.mjs: no globalThis.pdfjsWorker');
  return src.replace(/export\s*\{\s*WorkerMessageHandler\s*\}\s*;?\s*$/, '');
}

// Inside an inline <script>, "</script" would end the block early.
const safe = s => s.replace(/<\/script/gi, '<\\/script');

function main() {
  const pkg = pdfjsPackage();
  const version = JSON.parse(fs.readFileSync(path.join(pkg, 'package.json'), 'utf8')).version;
  if (version !== PDFJS_VERSION) throw new Error(`got pdfjs-dist ${version}, wanted ${PDFJS_VERSION}`);
  const lib = fs.readFileSync(path.join(pkg, 'legacy', 'build', 'pdf.min.mjs'), 'utf8');
  const worker = fs.readFileSync(path.join(pkg, 'legacy', 'build', 'pdf.worker.min.mjs'), 'utf8');
  const layout = fs.readFileSync(path.join(ROOT, 'shared', 'pdf_text_layout.js'), 'utf8');
  const sha = s => crypto.createHash('sha256').update(s).digest('hex').slice(0, 16);

  const body = [
    '// GENERATED by tools/gen_pdfjs_inline.js - do not edit.',
    `// pdf.js ${PDFJS_VERSION} (pdfjs-dist legacy build; Apache-2.0, Copyright Mozilla Foundation - the`,
    '// licence notice is kept at the top of each inlined file) + shared/pdf_text_layout.js.',
    `// sha256/16: pdf.min.mjs ${sha(lib)}, pdf.worker.min.mjs ${sha(worker)}`,
    '/* eslint-disable */',
    `exports.PDFJS_VERSION = ${JSON.stringify(PDFJS_VERSION)};`,
    `exports.PDFJS_WORKER_JS = ${JSON.stringify(safe(workerAsGlobal(worker)))};`,
    `exports.PDFJS_LIB_JS = ${JSON.stringify(safe(libAsGlobal(lib)))};`,
    `exports.PDF_LAYOUT_JS = ${JSON.stringify(safe(layout))};`,
    '',
  ].join('\n');
  fs.writeFileSync(OUT, body);
  console.log(`wrote ${path.relative(ROOT, OUT)} (${(body.length / 1024).toFixed(0)} KB, pdf.js ${version})`);
}

if (require.main === module) main();
module.exports = { pdfjsPackage, PDFJS_VERSION };
