#!/usr/bin/env python3
"""Copy the activity screen's shared files (shared/) into both apps.

    ./tools/gen_activity_view.py          # write the desktop and Android copies
    ./tools/gen_activity_view.py --check  # exit 1 if any copy differs from its source

Two sources, one place to edit:
  shared/activity_view.json      what each sport shows (metrics, charts, colours, palettes)
  shared/activity_view_logic.js  the maths both apps run (metric values, zones, colour bands,
                                 chart scales, "compared with your usual", swim benchmark)
  shared/activity_streams.js     the FIT decoder for Android (twin of tools/activity_streams.py,
                                 checked by tools/test_activity_streams_parity.js)
  shared/activity_chart_draw.js  how the charts are DRAWN (canvas calls), used by the desktop's QML
                                 Canvas and by the Android WebView chart page alike
Copies: the desktop embeds desktop/assets/activity_view.json (Qt resource) and imports
desktop/qml/ActivityViewLogic.js (QML needs a ".pragma library" first line, added here);
Android's bundler (Metro) only sees files inside android/, so it gets android/src/config/.
Editing a copy by hand is the drift this prevents (see the Android decoder-drift history).
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON_SRC = ROOT / "shared" / "activity_view.json"
LOGIC_SRC = ROOT / "shared" / "activity_view_logic.js"
STREAMS_SRC = ROOT / "shared" / "activity_streams.js"
DRAW_SRC = ROOT / "shared" / "activity_chart_draw.js"
PRAGMA = b".pragma library\n// GENERATED from shared/activity_view_logic.js by tools/gen_activity_view.py - edit that file.\n"
HEADER = b"// GENERATED from shared/activity_view_logic.js by tools/gen_activity_view.py - edit that file.\n"


def targets():
    j = JSON_SRC.read_bytes()
    json.loads(j)                                 # refuse to copy invalid JSON
    logic = LOGIC_SRC.read_bytes()
    return [(ROOT / "desktop" / "assets" / "activity_view.json", j),
            (ROOT / "android" / "src" / "config" / "activity_view.json", j),
            (ROOT / "desktop" / "qml" / "ActivityViewLogic.js", PRAGMA + logic),
            (ROOT / "android" / "src" / "config" / "activityViewLogic.js", HEADER + logic),
            (ROOT / "android" / "src" / "config" / "activityStreams.js",
             HEADER.replace(b"activity_view_logic.js", b"activity_streams.js") + STREAMS_SRC.read_bytes()),
            (ROOT / "desktop" / "qml" / "ActivityChartDraw.js",
             PRAGMA.replace(b"activity_view_logic.js", b"activity_chart_draw.js") + DRAW_SRC.read_bytes()),
            # also as a module, for the few helpers the app itself uses (the swim legend)
            (ROOT / "android" / "src" / "config" / "activityChartDraw.js",
             HEADER.replace(b"activity_view_logic.js", b"activity_chart_draw.js") + DRAW_SRC.read_bytes()),
            # the Android chart runs inside a WebView page, so it gets the drawing code (and the
            # logic it calls) as source text to inline into that page
            (ROOT / "android" / "src" / "config" / "activityChartSources.ts",
             b"// GENERATED by tools/gen_activity_view.py from shared/activity_view_logic.js and\n"
             b"// shared/activity_chart_draw.js - edit those files.\n"
             b"export const ACTIVITY_VIEW_LOGIC_SRC = " + json.dumps(logic.decode()).encode() + b";\n"
             b"export const ACTIVITY_CHART_DRAW_SRC = " + json.dumps(DRAW_SRC.read_text()).encode() + b";\n")]


def main():
    if "--check" in sys.argv:
        bad = [str(p.relative_to(ROOT)) for p, data in targets() if not p.exists() or p.read_bytes() != data]
        if bad:
            print("out of sync:", ", ".join(bad), "- run tools/gen_activity_view.py")
            sys.exit(1)
        print("activity view: every copy matches shared/")
        return
    for p, data in targets():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)
        print("wrote", p.relative_to(ROOT))


if __name__ == "__main__":
    main()
